### ISSUE TITLE
TASK: Create a Privacy Policy

### ISSUE THREAD

**Issue by andrew-fuchs** [cse442-fall-2019-offering/442projects-smart-city-finder#11]
I should be able to find a Privacy Policy that tells me:
  * The website does not (currently) permanently store any information about its users beyond normal server logs.
  * That the website does not collect information from children under the age of 13 (i.e. the site complies with COPPA).
  * That we may update the privacy policy and that the up-to-date version will be accessible from the website.

**Comment by siddharthbandhu** [comment]
I believe we need to set up a page for Terms and Conditions as well, which will go along with the Privacy Policy.

**Comment by andrew-fuchs** [comment]
Resolved by commit 993a33a
