### ISSUE TITLE
As a quiz taker, I want to be able to type the site's `/quiz/` url into my browser and be redirected to the landing page, so I can find the quiz and not be confused.

### ISSUE THREAD

**Issue by andrew-fuchs** [cse442-fall-2019-offering/442projects-smart-city-finder#30]
When I try to visit the site's "/quiz/" url by typing it into my address bar (and not submitting the form):
  * I should be redirected to the site's landing page

**Comment by hanmingliu2** [comment]
This issue is resolved by commit bd3806f and commit 05fa940, closing now.
